// Generated by CoffeeScript 1.7.1
(function() {
  (function(window) {
    var ImageBox;
    $.fn.extend({
      'imageBox': function(option, args) {
        var funk;
        funk = function($e) {
          var data;
          data = $e.data('imageBox');
          if (!data) {
            $e.data('imageBox', (data = new ImageBox($e, option)));
          }
          if (typeof option === 'string') {
            args = [].concat(args);
            return data[option].apply(data, args);
          }
        };
        if (this.length === 1) {
          return funk($(this));
        } else {
          return this.each(function() {
            return funk($(this));
          });
        }
      }
    });
    return ImageBox = (function() {
      ImageBox.prototype._backgroundSize = function() {
        var bs, e, _i, _len, _results;
        bs = this.$image.css('background-size').split(' ');
        _results = [];
        for (_i = 0, _len = bs.length; _i < _len; _i++) {
          e = bs[_i];
          _results.push(Number(e.replace('px', '')));
        }
        return _results;
      };

      ImageBox.prototype._backgroundPosition = function() {
        var bp, e, _i, _len, _results;
        bp = this.$image.css('background-position').split(' ');
        _results = [];
        for (_i = 0, _len = bp.length; _i < _len; _i++) {
          e = bp[_i];
          _results.push(Number(e.replace('px', '')));
        }
        return _results;
      };

      ImageBox.prototype._events = function() {
        var self;
        self = this;
        this.$image.on('mousewheel', function(e) {
          var h, pos, scaling, w;
          pos = Math.round(e.originalEvent.wheelDelta);
          if (pos > 0) {
            scaling = pos / 100;
          } else {
            scaling = pos / -200;
          }
          w = self._backgroundSize()[0] * scaling;
          h = self._backgroundSize()[1] * scaling;
          return self.resize(h, w);
        });
        this.$image.on('dblclick', function(e) {
          self.$image.css('background-position', '0px 0px');
          return self.resize(self.stockHeight, self.stockWidth);
        });
        return this.$image.on('mousedown', function(e) {
          var curX, curY, destroy, handler;
          curX = e.pageX - self._backgroundPosition()[0];
          curY = e.pageY - self._backgroundPosition()[1];
          handler = function(e) {
            var x, y;
            if (e.type !== 'mouseup') {
              x = Math.ceil(e.pageX - curX);
              y = Math.ceil(e.pageY - curY);
              return $(this).css('background-position', "" + x + "px " + y + "px");
            } else {
              return destroy();
            }
          };
          destroy = function() {
            return self.$image.off('mouseup mousemove', handler);
          };
          self.$image.on('mouseup mousemove', handler);
          return self.$image.on('mouseleave', destroy);
        });
      };

      function ImageBox(element, options) {
        this.element = element;
        options = options || {};
        this.stretchToCanvas = options.stretchToCanvas || true;
        this.stockHeight = this.element.height();
        this.stockWidth = this.element.width();
        this.image = document.createElement('div');
        this.$image = $(this.image);
        this.element.append(this.image);
        this.clearImage();
        this._events();
      }

      ImageBox.prototype.setImage = function(img) {
        var self, _image;
        self = this;
        _image = new Image();
        _image.addEventListener('load', function() {
          self.$image.css('background-image', "url('" + img + "')");
          self.$image.css('cursor', 'move');
          self.stockHeight = this.height;
          self.stockWidth = this.width;
          self.resize(this.height, this.width);
          return _image = null;
        });
        return _image.src = img;
      };

      ImageBox.prototype.resize = function(height, width) {
        var eHeight, eWidth, h, w;
        eWidth = this.element.width();
        eHeight = this.element.height();
        if (width <= eWidth && this.stretchToCanvas) {
          w = eWidth;
        } else {
          w = width;
        }
        if (height <= eHeight && this.stretchToCanvas) {
          h = eHeight;
        } else {
          h = height;
        }
        return this.$image.css('background-size', "" + w + "px  " + h + "px");
      };

      ImageBox.prototype.getXY = function() {
        var coords, elemH, elemW, imageX, imageY;
        imageX = this._backgroundPosition()[0];
        imageY = this._backgroundPosition()[1];
        elemH = this.element.height();
        elemW = this.element.width();
        return coords = {
          "W": this._backgroundSize()[0],
          "H": this._backgroundSize()[1],
          "X1": -1 * imageX,
          "X2": elemW + imageX,
          "Y1": -1 * imageX,
          "Y2": elemH + imageY
        };
      };

      ImageBox.prototype.clearImage = function() {
        this.$image.css('background-position', "0px 0px");
        this.$image.css('background-image', 'none');
        this.$image.css('-webkit-user-select', 'none');
        this.$image.css('-webkit-user-drag', 'none');
        this.$image.css('cursor', 'auto');
        this.$image.css('background-size', "0px 0px");
        this.$image.css('height', this.element.height());
        this.$image.css('width', this.element.width());
        this.$image.css('background-repeat', 'no-repeat no-repeat');
        return this.$image.css('border', 'none');
      };

      return ImageBox;

    })();
  })(window);

}).call(this);
